#参照ruicky/jd_sign_bot

name: Github dkd-auto-coin
 
on:
    push:
        branches:
            - master
    schedule:
        - cron: '0,10,20,30 * * * *'
jobs:
    build:
        runs-on: ubuntu-18.04
 
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run
              run: npm install
            - run: node node.js
              env:
                dkdurl: ${{ secrets.dkdurl }}
                dkdbody: ${{ secrets.dkdbody }}
                sckey: ${{ secrets.sckey }}
                dkdhd: ${{ secrets.dkdhd }}
            - name: Upload to this repo
              run: |
                git config --global user.name "多看点通知"
                git config --global user.email "wenmossux@gmail.com" 
                git add . 
                git commit -m '运行结果'  
                git push -u origin master
